### PR TITLE
Feature #109 Help and FAQ Page

### PR DESCRIPTION
**Pull request by pfrechFra**
First simple structure with accordion. Still some trouble with the wordwrapping regarding to our global css

### CODE REVIEW

**Review by DontEatMyCookies — COMMENTED** [review]
is "database/._mongo_storage" supposed to be in this PR?

**Comment by pfrechFra** [comment]
> is "database/._mongo_storage" supposed to be in this PR?

good question, don´t know why it´s even been there

**Comment by pfrechFra** [comment]
@antonroesler could you please check and merge?

**Comment by pfrechFra** [comment]
@DontEatMyCookies mongo_storage removed, please check again and merge if everything is fine

**Review by DontEatMyCookies — APPROVED** [review]

**Pull request merged**
